INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Alcohol Gel', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Almacenamiento ', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Ampolletas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Archivadores', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Bases', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Bienes Fungibles Controlables', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Bolsas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Calculadoras', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Carpetas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Cartulinas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Catridge', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Ceras', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Cintas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Correctores', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Cortantes', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Cuadernos', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Desinfectantes', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Desodorantes', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Dispensadores', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Elasticos', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Escritorio', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Esperiales', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Guantes', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Jabones', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Lapices', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Libretas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Libros', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Limpiadores', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Mata Insectos', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Mediciones', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Micas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Minas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Ordenadores', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Panos de Limpieza', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Papel Higienico', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Papeles', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Pegamentos', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Porta Objetos', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Protectores', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Reglas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Sobres', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Sujetadores de Papeles', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Tacos', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Tampones', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Timbres', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Tintas', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Toalla de Papel', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Toner', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Varios', ' ', now());
INSERT INTO `inventiolite`.`category` (`name`) VALUES ('Varios Informatica', ' ', now());
